# Generated by Django 3.2.5 on 2022-01-03 03:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfuser',
            name='friends',
            field=models.ManyToManyField(related_name='_users_golfuser_friends_+', through='friend.Friendship', to=settings.AUTH_USER_MODEL),
        ),
    ]
