# Generated by Django 3.2.5 on 2021-09-20 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', related_query_name='scorecard', to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='ScorecardHole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('par', models.PositiveSmallIntegerField()),
                ('distance', models.PositiveSmallIntegerField()),
                ('handicap', models.PositiveSmallIntegerField()),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecard_holes', related_query_name='scorecard_hole', to='course.scorecard')),
            ],
        ),
    ]
