# Generated by Django 3.2.5 on 2021-12-13 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('round', '0001_initial'), ('round', '0002_rename_userround_registration'), ('round', '0003_alter_round_course'), ('round', '0004_switch_user_round_for_registration'), ('round', '0005_alter_score_registration'), ('round', '0006_big_shake_up'), ('round', '0007_big_shake_up_finalized')]

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=500)),
                ('tee_time', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rounds', related_query_name='round', to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='UserRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.BooleanField(default=False)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rounds', related_query_name='user_round', to='round.round')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rounds', related_query_name='user_round', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', related_query_name='score', to='round.round')),
                ('scorecard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', related_query_name='score', to='course.scorecard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', related_query_name='score', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='round',
            name='users',
            field=models.ManyToManyField(through='round.UserRound', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('strokes', models.PositiveSmallIntegerField()),
                ('par', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('distance', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('handicap', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holes', related_query_name='holes', to='round.score')),
            ],
        ),
        migrations.AddConstraint(
            model_name='userround',
            constraint=models.UniqueConstraint(condition=models.Q(('creator', True)), fields=('round',), name='single_creator'),
        ),
        migrations.RenameModel(
            old_name='UserRound',
            new_name='Registration',
        ),
        migrations.AlterField(
            model_name='round',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', related_query_name='round', to='course.course'),
        ),
        migrations.RemoveField(
            model_name='score',
            name='round',
        ),
        migrations.RemoveField(
            model_name='score',
            name='user',
        ),
        migrations.AddField(
            model_name='score',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', related_query_name='registration', to='round.registration'),
        ),
        migrations.RemoveField(
            model_name='score',
            name='scorecard',
        ),
        migrations.AddField(
            model_name='round',
            name='scorecard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', related_query_name='round', to='course.scorecard'),
        ),
        migrations.AddField(
            model_name='score',
            name='scorecard_hole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', related_query_name='score', to='course.scorecardhole'),
        ),
        migrations.AddField(
            model_name='score',
            name='strokes',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.DeleteModel(
            name='Hole',
        ),
    ]
