# Generated by Django 3.2.5 on 2022-01-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0002_alter_round_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='accepted',
            field=models.BooleanField(null=True),
        ),
    ]
