# Generated by Django 3.2.5 on 2022-01-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0003_registration_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
